default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  port: 3306
  username: root  
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: flying_holander_development

test:
  <<: *default
  database: flying_holander_test


  production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: flying_holander_production
  pool: 5
  username: root
  password: 
  host: 127.0.0.1
